mode:
  test: False

model:
  name: 'fourier_series'
  n: 3
  dilation: False
  # it is naive method

dataset:
  type: 'sine'
  path: './datasets/csv/unit_amp_freq10_nosign_600.csv'
  batch: 1
  interpolation: 300
  extrapolation: 300

debug: False
exid : 'fourier_series_1126'
gpus: None