mode:
  test: False

model:
  name: 'generative'
  optimizer: 'ADAM'
  in_feature: 1
  out_feature: 1
  latent_dim: 2
  hidden_dim: 128
  expansion_type: 'fourier'
  n_harmonics: 12
  n_eig: 2 # cos + sin

dataset:
  type: 'sine'
  path: './datasets/csv/unit_amp_freq10_nosign.csv'
  batch: 64

gpus: '1' # str required
debug: False

exid : 'unit_amp_10freq_test_2layer'