mode:
  test: False

model:
  name: 'generative'
  optimizer: 'ADAM'
  in_feature: 1
  out_feature: 1
  latent_dim: 3
  hidden_dim: 512
  expansion_type: 'fourier'
  n_harmonics: 50
  n_eig: 2 # weight + bias

dataset:
  type: 'sine'
  path: './datasets/csv/unit_amp_freq20.csv'
  batch: 64

gpus: '3' # str required
debug: False

exid : 'unit_amp_20freq_test'