mode:
  test: False

model:
  name: 'irregular'
  optimizer: 'ADAM'
  in_feature: 1
  out_feature: 1
  latent_dim: 4
  hidden_dim: 64
  expansion_type: 'fourier'
  n_harmonics: 6
  n_eig: 2 # weight + bias
  har_mode: 4
  merger: True
  all_element_wise: False

dataset:
  type: 'irregular'
  path: './datasets/csv/1217_sin2x_cosx.csv'
  batch: 64
  interpolation: 1000
  extrapolation: 1000

gpus: '2' # str required
debug: False

exid : 'merger_011112_test'