mode:
  test: False

model:
  name: 'rmsn'
  phase: 3
  cs_hidden_dim : 10
  st_hidden_dim : 10
  intervention_dim : 6
  observation_dim : 3
  latent_dim : 16

  layer : 1
  optimizer : 'ADAM'

  encoder_dim : 62
  encoder_lr : 0.0001
  encoder_epoch : 1000

  decoder_hidden_dim : 62
  decoder_lr : 0.0001
  decoder_epoch : 1000

tuning_test: False
dataset:
  type: 'mimic'
  batch: 32

  truncate: False
  projection_horizon : 5  # in RMSN settings
  trunc_path: './rmsn_decoder_dataset/1224_test_3/'
  truncated_batch: 128   # corresponding to batch 64
  truncated_one_series: 47


gpus: '3' # str required
debug: False
tte: 0.1 # time to encode
exid : '0111_CHIL_mimic'